// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgsnxqrunvjzgjowoawh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nc254cXJ1bnZqemdqb3dvYXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODA3NjksImV4cCI6MjA2NjI1Njc2OX0.zjAkanD0qOTUgaaMDCkOnQ6O7gtbSlm2KasIurFKLsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);